# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib ivrobustness, .registration = TRUE
NULL

CovarianceMatrix <- new.env(parent = emptyenv())

CovarianceMatrix$new <- function(w, z, y) .Call(wrap__CovarianceMatrix__new, w, z, y)

CovarianceMatrix$iv_estimate <- function() .Call(wrap__CovarianceMatrix__iv_estimate, self)

CovarianceMatrix$soo_estimate <- function() .Call(wrap__CovarianceMatrix__soo_estimate, self)

CovarianceMatrix$to_r_mat <- function() .Call(wrap__CovarianceMatrix__to_r_mat, self)

CovarianceMatrix$extend <- function(params) .Call(wrap__CovarianceMatrix__extend, self, params)

CovarianceMatrix$exogenous_iv_rv <- function(b_iv) .Call(wrap__CovarianceMatrix__exogenous_iv_rv, self, b_iv)

CovarianceMatrix$excludable_iv_rv <- function(b_iv) .Call(wrap__CovarianceMatrix__excludable_iv_rv, self, b_iv)

CovarianceMatrix$iv_rv <- function(b_iv) .Call(wrap__CovarianceMatrix__iv_rv, self, b_iv)

CovarianceMatrix$soo_rv <- function(b_soo) .Call(wrap__CovarianceMatrix__soo_rv, self, b_soo)

CovarianceMatrix$calc_iv_rv_with_se <- function(w, z, y, b_iv) .Call(wrap__CovarianceMatrix__calc_iv_rv_with_se, w, z, y, b_iv)

#' @export
`$.CovarianceMatrix` <- function (self, name) { func <- CovarianceMatrix[[name]]; environment(func) <- environment(); func }

#' @export
`[[.CovarianceMatrix` <- `$.CovarianceMatrix`

ExtendedCovarianceMatrix <- new.env(parent = emptyenv())

ExtendedCovarianceMatrix$to_r_mat <- function() .Call(wrap__ExtendedCovarianceMatrix__to_r_mat, self)

ExtendedCovarianceMatrix$soo_estimate <- function() .Call(wrap__ExtendedCovarianceMatrix__soo_estimate, self)

ExtendedCovarianceMatrix$iv_estimate <- function() .Call(wrap__ExtendedCovarianceMatrix__iv_estimate, self)

ExtendedCovarianceMatrix$tau <- function() .Call(wrap__ExtendedCovarianceMatrix__tau, self)

ExtendedCovarianceMatrix$soo_z <- function() .Call(wrap__ExtendedCovarianceMatrix__soo_z, self)

ExtendedCovarianceMatrix$soo_y <- function() .Call(wrap__ExtendedCovarianceMatrix__soo_y, self)

ExtendedCovarianceMatrix$iv_z <- function() .Call(wrap__ExtendedCovarianceMatrix__iv_z, self)

ExtendedCovarianceMatrix$iv_y <- function() .Call(wrap__ExtendedCovarianceMatrix__iv_y, self)

#' @export
`$.ExtendedCovarianceMatrix` <- function (self, name) { func <- ExtendedCovarianceMatrix[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ExtendedCovarianceMatrix` <- `$.ExtendedCovarianceMatrix`

# nolint end
